#docker-compose.yml
version: '2' # 表示该 Docker-Compose 文件使用的是 Version 2 file
services:
  pvfront:  # 指定服务名称
    build: .  # 指定 Dockerfile 所在路径
    ports:    # 指定端口映射
      - "8099:8099/tcp"
      - "12345:12345/udp"
      - "12344:12344/udp"
