server:
  port: 8080
spring:
  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
  data:
    neo4j:
      uri: http://tx.njqiteng.club:7474
      username: neo4j
      password: 12345678
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123

