server:
  port: 8099
spring:
  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/

# data:
#    neo4j:
#      uri: http://148.70.64.121:7474
      #uri: http://10.1.3.251:7474
#      username: neo4j
#      password: 12345678
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: pvtest
    password: 123
systemparam:
  #web-server-ip: "192.168.2.1"
  web-server-ip: "10.1.3.35"
  web-server-port: 12333
  web-listen-port: 12343
  front-server-port: 12388

  polling-interval: 1
  heart-interval: 1
  ftmId: 1 #前置机ID号

  energy-web-server-ip: "10.1.3.35"
  energy-web-server-port: 12333
  energy-web-listen-port: 12344
  energy-front-server-port: 12389


mqtt:
  url: tcp://10.1.3.249:1883   #服务器地址
  topic: pvrpt