server:
  port: 8099
spring:
  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
  data:
    neo4j:
      uri: http://148.70.64.121:7474
      #uri: http://10.1.3.251:7474
      username: neo4j
      password: 12345678
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: pvtest
    password: 123
systemparam:
  web-server-ip: "127.0.0.1"
  web-server-port: 12333
  front-server-port: 12345
  polling-interval: 1
  heart-interval: 1


